# Generated by Django 5.2.5 on 2025-08-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeIdSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'employee_id_sequences',
            },
        ),
    ]
