# Generated by Django 5.2.5 on 2025-08-19 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employeeidsequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='core.patient'),
        ),
    ]
