# Generated by Django 5.2.5 on 2025-08-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_bill_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('super_user', 'Super User'), ('operation_manager', 'Operation Manager'), ('pharmacy_manager', 'Pharmacy Manager'), ('receptionist', 'Receptionist'), ('staff', 'Staff'), ('cro', 'CRO')], max_length=20),
        ),
    ]
