# Generated by Django 5.2.5 on 2025-08-21 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='treatment_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='core.treatmentplan'),
        ),
    ]
