# Generated by Django 5.2.5 on 2025-08-23 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_followup_treatment_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='state',
            new_name='district',
        ),
    ]
