# Generated by Django 5.2.5 on 2025-08-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_state_patient_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
