# Generated by Django 5.2.5 on 2025-08-23 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_patient_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentplan',
            name='clinician_signature',
        ),
        migrations.RemoveField(
            model_name='treatmentplan',
            name='patient_consent_signature',
        ),
    ]
