# Generated by Django 5.2.5 on 2025-08-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_treatmentplan_clinician_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='sittings',
            field=models.CharField(blank=True, choices=[('first', 'First Sitting'), ('second', 'Second Sitting'), ('boost', 'Booster'), ('repeat', 'Repeat'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=15),
        ),
    ]
