# Generated by Django 5.2.5 on 2025-08-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_appointment_sittings_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='sittings',
            field=models.CharField(choices=[('first', 'First Sitting'), ('second', 'Second Sitting'), ('boost', 'Booster'), ('repeat', 'Repeat'), ('other', 'Other')], default='first', max_length=20),
        ),
    ]
