# Generated by Django 5.2.5 on 2025-08-25 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_appointment_sittings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='assigned_staff',
        ),
    ]
