# Generated by Django 5.2.5 on 2025-08-27 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_service_alter_bill_options_remove_bill_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('service', 'Service'), ('pharmacy', 'Pharmacy')], default='service', max_length=10),
        ),
        migrations.AddField(
            model_name='billitem',
            name='kind',
            field=models.CharField(blank=True, choices=[('service', 'Service'), ('pharmacy', 'Medicine')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='billitem',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bill_items', to='core.medicine'),
        ),
    ]
