# Generated by Django 5.2.5 on 2025-08-27 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_bill_bill_type_billitem_kind_billitem_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='code',
        ),
    ]
