# Generated by Django 5.2.5 on 2025-08-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_service_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='code',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
