# Generated by Django 5.2.5 on 2025-08-27 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_service_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitem',
            name='description',
        ),
    ]
