# Generated by Django 5.2.5 on 2025-08-27 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_billitem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='appointment',
        ),
    ]
