# Generated by Django 5.2.5 on 2025-08-27 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_bill_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='patient',
            field=models.ForeignKey(default='c7bfe752b0964109a73d10f93cc39a05', on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='core.patient'),
            preserve_default=False,
        ),
    ]
