# Generated by Django 5.2.5 on 2025-08-27 10:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_bill_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], max_length=15),
        ),
        migrations.AddField(
            model_name='billitem',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
