# Generated by Django 5.2.5 on 2025-08-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_bill_paid_amount_bill_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='assigned_cro',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='budget_range',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='hair_loss_concern',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='previous_treatments',
        ),
    ]
