# Generated by Django 5.2.5 on 2025-09-02 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_lead_assigned_cro_remove_lead_budget_range_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='receipt_image',
            new_name='attachment',
        ),
    ]
