# Generated by Django 5.2.1 on 2025-09-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_receipt_image_expense_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='conversion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_contact_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='next_followup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
