# Generated by Django 5.2.1 on 2025-09-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_lead_conversion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='followup_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='followup',
            name='next_followup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
