# Generated by Django 5.2.1 on 2025-09-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_followup_followup_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='remark',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('cheque', 'Cheque')], max_length=15),
        ),
    ]
