# Generated by Django 5.2.1 on 2025-09-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_bill_remark_alter_bill_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='duration_minutes',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='sittings',
            field=models.CharField(choices=[('first', 'First Sitting'), ('second', 'Second Sitting'), ('boost', 'Booster'), ('repeat_first', 'Repeat First'), ('repeat_second', 'Repeat Second'), ('gfc', 'GFC'), ('other', 'Other')], default='first', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=15),
        ),
    ]
