# Generated by Django 5.2.1 on 2025-09-15 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_appointment_duration_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('status', 'Status Change'), ('reschedule', 'Reschedule')], max_length=20)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('from_datetime', models.DateTimeField(blank=True, null=True)),
                ('to_datetime', models.DateTimeField(blank=True, null=True)),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(blank=True, default='', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.appointment')),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
