# Generated by Django 5.2.1 on 2025-09-16 09:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_appointmentlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('reschedule', 'Reschedule'), ('cancel', 'Cancel'), ('complete', 'Complete')], max_length=20),
        ),
        migrations.CreateModel(
            name='PatientAccountEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('charge', 'Charge (Bill Total)'), ('payment', 'Payment Received'), ('advance_deposit', 'Advance Deposit'), ('advance_applied', 'Advance Applied to Bill'), ('advance_refund', 'Advance Refund to Patient'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_entries', to='core.bill')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_entries', to='core.patient')),
            ],
            options={
                'db_table': 'patient_account_entries',
                'indexes': [models.Index(fields=['patient', 'kind'], name='patient_acc_patient_3ba364_idx'), models.Index(fields=['bill'], name='patient_acc_bill_id_0831d5_idx'), models.Index(fields=['created_at'], name='patient_acc_created_33c50c_idx')],
            },
        ),
    ]
