# Generated by Django 5.2.1 on 2025-09-16 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_appointmentlog_action_patientaccountentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientAccountEntry',
        ),
    ]
