# Generated by Django 5.2.5 on 2025-09-17 07:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_delete_patientaccountentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
