# Generated by Django 5.2.5 on 2025-09-17 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_patient_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='balance',
        ),
    ]
