# Generated by Django 5.2.5 on 2025-09-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_payment_allocation_group_payment_memo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='allocation_group',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='origin_bill',
        ),
    ]
