# Generated by Django 5.2.5 on 2025-09-18 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_payment_allocation_group_remove_payment_memo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='allocation_group',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='memo',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='origin_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_allocations', to='core.bill'),
        ),
    ]
