# Generated by Django 5.2.5 on 2025-09-20 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_bill_is_void_bill_remark_payment_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='core.patient'),
        ),
    ]
