# Generated by Django 5.2.5 on 2025-09-20 08:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_bill_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='billitem',
            name='session',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='tag',
        ),
        migrations.AddField(
            model_name='bill',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='bill',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='core.patient'),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='kind',
            field=models.CharField(choices=[('service', 'Service'), ('pharmacy', 'Medicine')], max_length=10),
        ),
        migrations.DeleteModel(
            name='LedgerEntry',
        ),
    ]
