# Generated by Django 5.2.5 on 2025-09-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_bill_discount_amount_bill_tax_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('consulting_doctor', 'Consulting Doctor'), ('super_user', 'Super User'), ('operation_manager', 'Operation Manager'), ('pharmacy_manager', 'Pharmacy Manager'), ('receptionist', 'Receptionist'), ('staff', 'Staff'), ('cro', 'CRO')], max_length=20),
        ),
        migrations.DeleteModel(
            name='AppointmentSlot',
        ),
    ]
