# Generated by Django 5.2.1 on 2025-10-04 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_branch_appointment_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentplan',
            name='procedure_type',
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='procedure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plans', to='core.service'),
            preserve_default=False,
        ),
    ]
