# Generated by Django 5.2.5 on 2025-10-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_treatmentplan_procedure_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date'], 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterModelOptions(
            name='appointmentlog',
            options={'verbose_name_plural': 'Appointment Logs'},
        ),
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-bill_date'], 'verbose_name_plural': 'Bills'},
        ),
        migrations.AlterModelOptions(
            name='billitem',
            options={'verbose_name_plural': 'Bill Items'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['name'], 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='consultationphoto',
            options={'verbose_name_plural': 'Consultation Photos'},
        ),
        migrations.AlterModelOptions(
            name='dailyreport',
            options={'ordering': ['-report_date'], 'verbose_name_plural': 'Daily Reports'},
        ),
        migrations.AlterModelOptions(
            name='employeeidsequence',
            options={'verbose_name_plural': 'Employee ID Sequences'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date'], 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='followup',
            options={'verbose_name_plural': 'Follow Ups'},
        ),
        migrations.AlterModelOptions(
            name='hairconsultation',
            options={'verbose_name_plural': 'Hair Consultations'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Leads'},
        ),
        migrations.AlterModelOptions(
            name='leadsource',
            options={'verbose_name_plural': 'Lead Sources'},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name_plural': 'Medicines'},
        ),
        migrations.AlterModelOptions(
            name='medicinestock',
            options={'verbose_name_plural': 'Medicine Stocks'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterModelOptions(
            name='patientmedicalhistory',
            options={'verbose_name_plural': 'Patient Medical Histories'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='progressphoto',
            options={'verbose_name_plural': 'Progress Photos'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='stocktransaction',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Stock Transactions'},
        ),
        migrations.AlterModelOptions(
            name='treatmentplan',
            options={'verbose_name_plural': 'Treatment Plans'},
        ),
        migrations.AlterModelOptions(
            name='treatmentsession',
            options={'verbose_name_plural': 'Treatment Sessions'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='sittings',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('first', 'First Sitting'), ('second', 'Second Sitting'), ('boost', 'Booster'), ('repeat_first', 'Repeat First'), ('repeat_second', 'Repeat Second'), ('gfc', 'GFC'), ('other', 'Other')], default='consultation', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
